/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hy_report_api_Food */

#ifndef _Included_com_hy_report_api_Food
#define _Included_com_hy_report_api_Food
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hy_report_api_Food
 * Method:    setFoodParam
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_hy_report_api_Food_setFoodParam
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_hy_report_api_Food
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hy_report_api_Food_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_hy_report_api_Food
 * Method:    getPrice
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_hy_report_api_Food_getPrice
  (JNIEnv *, jobject);

/*
 * Class:     com_hy_report_api_Food
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hy_report_api_Food_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
